//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class Assignments
    {
        /// <summary>pnlMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>lblMsg control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>gvUsers control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;

        /// <summary>pnlAssign control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAssign;

        /// <summary>litAssignUser control.</summary>
        protected global::System.Web.UI.WebControls.Literal litAssignUser;

        /// <summary>hfUserId control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfUserId;

        /// <summary>cblPartners control.</summary>
        protected global::System.Web.UI.WebControls.CheckBoxList cblPartners;

        /// <summary>btnSaveAssign control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSaveAssign;
    }
}
