//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class Assignments
    {
        /// <summary>pnlMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>lblMsg control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>ddlUser control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlUser;

        /// <summary>pnlPartners control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPartners;

        /// <summary>cblPartners control.</summary>
        protected global::System.Web.UI.WebControls.CheckBoxList cblPartners;

        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
