//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class AuditLog
    {
        /// <summary>pnlFilter control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFilter;

        /// <summary>txtFrom control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFrom;

        /// <summary>txtTo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTo;

        /// <summary>btnRun control.</summary>
        protected global::System.Web.UI.WebControls.Button btnRun;

        /// <summary>gvAudit control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvAudit;
    }
}
