//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class ChangePassword
    {
        /// <summary>pnlMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>lblMsg control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>txtCurrent control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrent;

        /// <summary>txtNew control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNew;

        /// <summary>txtConfirm control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
