//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class Dashboard
    {
        /// <summary>txtFrom control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFrom;

        /// <summary>txtTo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTo;

        /// <summary>btnApply control.</summary>
        protected global::System.Web.UI.WebControls.Button btnApply;

        /// <summary>litTotal control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>litTotalAmt control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalAmt;

        /// <summary>litRecon control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRecon;

        /// <summary>litReconAmt control.</summary>
        protected global::System.Web.UI.WebControls.Literal litReconAmt;

        /// <summary>litFailed control.</summary>
        protected global::System.Web.UI.WebControls.Literal litFailed;

        /// <summary>litFailedAmt control.</summary>
        protected global::System.Web.UI.WebControls.Literal litFailedAmt;

        /// <summary>litPending control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPending;

        /// <summary>litRate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRate;

        /// <summary>gvReasons control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvReasons;

        /// <summary>litChartScript control.</summary>
        protected global::System.Web.UI.WebControls.Literal litChartScript;
    }
}
