//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class ForgotPassword
    {
        /// <summary>pnlMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>lblMsg control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>pnlRequest control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlRequest;

        /// <summary>txtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>btnSendCode control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSendCode;

        /// <summary>pnlReset control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlReset;

        /// <summary>hfEmail control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEmail;

        /// <summary>txtOtp control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtOtp;

        /// <summary>txtNew control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNew;

        /// <summary>txtConfirm control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        /// <summary>btnReset control.</summary>
        protected global::System.Web.UI.WebControls.Button btnReset;
    }
}
