//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class Reports
    {
        /// <summary>pnlFilter control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFilter;

        /// <summary>txtFrom control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFrom;

        /// <summary>txtTo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTo;

        /// <summary>ddlChannel control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlChannel;

        /// <summary>btnRun control.</summary>
        protected global::System.Web.UI.WebControls.Button btnRun;

        /// <summary>btnExportSuccess control.</summary>
        protected global::System.Web.UI.WebControls.Button btnExportSuccess;

        /// <summary>btnExportFailed control.</summary>
        protected global::System.Web.UI.WebControls.Button btnExportFailed;

        /// <summary>btnExportUnrecon control.</summary>
        protected global::System.Web.UI.WebControls.Button btnExportUnrecon;

        /// <summary>litTotal control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>litRecon control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRecon;

        /// <summary>litFailed control.</summary>
        protected global::System.Web.UI.WebControls.Literal litFailed;

        /// <summary>litRate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRate;

        /// <summary>litUnrecon control.</summary>
        protected global::System.Web.UI.WebControls.Literal litUnrecon;

        /// <summary>gvReport control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvReport;
    }
}
