//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class Search
    {
        /// <summary>pnlFilter control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFilter;

        /// <summary>txtFrom control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFrom;

        /// <summary>txtTo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTo;

        /// <summary>ddlChannel control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlChannel;

        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>litCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCount;

        /// <summary>gvResults control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvResults;
    }
}
