//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class SiteMaster
    {
        /// <summary>HeadContent placeholder.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>litTopName control (name shown in the top bar).</summary>
        protected global::System.Web.UI.WebControls.Literal litTopName;

        /// <summary>liUsers control (admin-only menu item).</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor liUsers;

        /// <summary>litInitials control.</summary>
        protected global::System.Web.UI.WebControls.Literal litInitials;

        /// <summary>litUserName control.</summary>
        protected global::System.Web.UI.WebControls.Literal litUserName;

        /// <summary>litRole control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRole;

        /// <summary>btnLogout control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        /// <summary>MainContent placeholder.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>ScriptsContent placeholder.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
