//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultichoiceReconPortal
{
    public partial class Upload
    {
        /// <summary>pnlMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>lblMsg control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>ddlChannel control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlChannel;

        /// <summary>fuStatement control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuStatement;

        /// <summary>btnUpload control.</summary>
        protected global::System.Web.UI.WebControls.Button btnUpload;

        /// <summary>gvRecent control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvRecent;
    }
}
